name: pos_manangement_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  iconsax: 0.0.8
  iconly: ^1.0.1
  logger: ^2.0.2+1
  awesome_snackbar_content: ^0.1.3
  intl_phone_field: ^3.2.0
  lottie: ^2.7.0
  pinput: ^3.0.1
  google_fonts: ^6.1.0
  marquee_widget: 1.2.0
  focused_menu: 1.0.5
  flutter:
    sdk: flutter
  after_layout: ^1.2.0
  shimmer: ^3.0.0
  flutter_zoom_drawer: ^3.1.1
  page_transition: ^2.1.0

  dropdown_button2: ^2.3.9

  flutter_staggered_animations: ^1.1.1
  expandable_text: ^2.3.0
  like_button: ^2.0.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0
  flutter_barcode_scanner: ^2.0.0
  badges: ^3.1.2
  fluttertoast: ^8.2.4
  money_formatter: ^0.0.5

  loadmore: ^2.1.0
  flutter_rating_bar: ^4.0.1
  device_preview: ^1.1.0
  coupon_uikit: ^0.2.0
  intl: ^0.18.1
  photo_view: ^0.14.0
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.4
  api_cache_manager: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo/
    - assets/images/
    - assets/fonts/
    - lib/app/data/
    - assets/animations/
  fonts:
    - family: Metrophobic
      fonts:
        - asset: assets/fonts/Metrophobic-Regular.ttf
  uses-material-design: true
